# Generated by Django 6.0 on 2026-01-05 05:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description_fr', models.TextField(blank=True)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('description_uk', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('favourited_by', models.ManyToManyField(blank=True, related_name='favourite_items', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('button_text', models.CharField(max_length=10)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.item')),
                ('author', models.CharField(max_length=100)),
                ('author_fr', models.CharField(blank=True, max_length=100)),
                ('author_uk', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('biography', 'Biography'), ('autobiography', 'Autobiography'), ('history', 'History'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('science', 'Science'), ('technology', 'Technology'), ('health', 'Health & Fitness'), ('cooking', 'Cooking'), ('travel', 'Travel'), ('sports', 'Sports'), ('politics', 'Politics'), ('economics', 'Economics'), ('religion', 'Religion'), ('self_help', 'Self Help'), ('business', 'Business'), ('education', 'Education'), ('children', "Children's Books"), ('young_adult', 'Young Adult'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('classics', 'Classics'), ('contemporary', 'Contemporary Fiction'), ('historical_fiction', 'Historical Fiction'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('humor', 'Humor'), ('arts', 'Arts & Music'), ('reference', 'Reference'), ('other', 'Other')], max_length=50)),
                ('theme', models.CharField(blank=True, choices=[('love', 'Love & Romance'), ('betrayal', 'Betrayal'), ('redemption', 'Redemption'), ('coming_of_age', 'Coming of Age'), ('good_vs_evil', 'Good vs Evil'), ('identity', 'Identity & Self-Discovery'), ('survival', 'Survival'), ('family', 'Family & Relationships'), ('friendship', 'Friendship & Loyalty'), ('power_corruption', 'Power & Corruption'), ('revenge', 'Revenge'), ('sacrifice', 'Sacrifice'), ('freedom', 'Freedom & Liberation'), ('justice', 'Justice & Morality'), ('war', 'War & Conflict'), ('death_mortality', 'Death & Mortality'), ('hope', 'Hope & Perseverance'), ('faith_spirituality', 'Faith & Spirituality'), ('social_class', 'Social Class & Inequality'), ('prejudice', 'Prejudice & Discrimination'), ('loss_grief', 'Loss & Grief'), ('transformation', 'Transformation & Change'), ('destiny_fate', 'Destiny & Fate'), ('isolation', 'Isolation & Loneliness'), ('courage', 'Courage & Heroism')], max_length=50)),
                ('audience', models.CharField(blank=True, choices=[('children', 'Children'), ('young_adult', 'Young Adult'), ('adult', 'Adult'), ('general', 'General Audience')], max_length=50)),
                ('tone', models.CharField(blank=True, choices=[('light', 'Light & Humorous'), ('dark', 'Dark & Serious'), ('satirical', 'Satirical & Ironic'), ('romantic', 'Romantic & Sentimental'), ('mysterious', 'Mysterious & Suspenseful'), ('optimistic', 'Optimistic & Uplifting'), ('pessimistic', 'Pessimistic & Bleak'), ('whimsical', 'Whimsical & Fantastical'), ('nostalgic', 'Nostalgic & Reflective'), ('serene', 'Serene & Peaceful')], max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('uk', 'Ukrainian')], default='en', max_length=10)),
                ('language_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.item',),
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_date', models.DateField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='base.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(default=datetime.datetime(2026, 1, 10, 5, 16, 55, 235597, tzinfo=datetime.timezone.utc))),
                ('received', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(default=datetime.datetime(2026, 1, 24, 5, 16, 55, 235597, tzinfo=datetime.timezone.utc))),
                ('unlimited_loan', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.creativework')),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.creativework',),
        ),
    ]
