# Generated by Django 5.2.9 on 2025-12-27 00:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('button_text', models.CharField(max_length=10)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.AddField(
            model_name='item',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 12, 27, 0, 54, 30, 263622, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 10, 0, 54, 23, 251040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 0, 54, 23, 251000, tzinfo=datetime.timezone.utc)),
        ),
    ]
