# Generated by Django 5.2.9 on 2025-12-28 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_loan_due_date_alter_loan_loan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 7, 14, 43, 114850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 7, 14, 43, 114809, tzinfo=datetime.timezone.utc)),
        ),
    ]
