# Generated by Django 6.0 on 2026-01-05 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 24, 20, 49, 25, 280392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 10, 20, 49, 25, 279846, tzinfo=datetime.timezone.utc)),
        ),
    ]
