# Generated by Django 6.0 on 2025-12-29 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_loan_due_date_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 12, 6, 46, 21, 795705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 6, 46, 21, 795705, tzinfo=datetime.timezone.utc)),
        ),
    ]
