# Generated by Django 6.0 on 2026-01-05 20:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_image_alter_loan_due_date_alter_loan_loan_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 24, 20, 53, 34, 431950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 10, 20, 53, 34, 431950, tzinfo=datetime.timezone.utc)),
        ),
    ]
