# Generated by Django 6.0 on 2026-01-08 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_interested_users_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 24, 2, 12, 11, 719975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 10, 2, 12, 11, 719975, tzinfo=datetime.timezone.utc)),
        ),
    ]
