# Generated by Django 6.0 on 2025-12-30 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_item_image_alter_loan_due_date_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 4, 47, 43, 138282, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 4, 47, 43, 138282, tzinfo=datetime.timezone.utc)),
        ),
    ]
