# Generated by Django 6.0 on 2025-12-30 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_genre_item_language_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 4, 56, 38, 816744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 4, 56, 38, 816744, tzinfo=datetime.timezone.utc)),
        ),
    ]
