# Generated by Django 6.0 on 2026-01-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_loan_due_date_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 31, 21, 17, 51, 125749, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 21, 17, 51, 125749, tzinfo=datetime.timezone.utc)),
        ),
    ]
