# Generated by Django 6.0 on 2025-12-30 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_item_total_copies_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science fiction'), ('history', 'History')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 17, 6, 19, 865369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 17, 6, 19, 865369, tzinfo=datetime.timezone.utc)),
        ),
    ]
