# Generated by Django 6.0 on 2025-12-30 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_item_genre_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 17, 17, 15, 956791, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 17, 17, 15, 956791, tzinfo=datetime.timezone.utc)),
        ),
    ]
