# Generated by Django 6.0 on 2025-12-30 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_item_language_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('uk', 'Ukrainian')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 17, 48, 15, 905320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 17, 48, 15, 905320, tzinfo=datetime.timezone.utc)),
        ),
    ]
