# Generated by Django 6.0 on 2025-12-30 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_item_language_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author_fr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='author_uk',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description_uk',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title_fr',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title_uk',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('biography', 'Biography'), ('autobiography', 'Autobiography'), ('history', 'History'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('science', 'Science'), ('technology', 'Technology'), ('health', 'Health & Fitness'), ('cooking', 'Cooking'), ('travel', 'Travel'), ('sports', 'Sports'), ('politics', 'Politics'), ('economics', 'Economics'), ('religion', 'Religion'), ('self_help', 'Self Help'), ('business', 'Business'), ('education', 'Education'), ('children', "Children's Books"), ('young_adult', 'Young Adult'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('classics', 'Classics'), ('contemporary', 'Contemporary Fiction'), ('historical_fiction', 'Historical Fiction'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('humor', 'Humor'), ('arts', 'Arts & Music'), ('reference', 'Reference'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 18, 28, 40, 942495, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 18, 28, 40, 942495, tzinfo=datetime.timezone.utc)),
        ),
    ]
