# Generated by Django 6.0 on 2026-01-14 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_loan_due_date_alter_loan_loan_date'),
        ('recommendations', '0005_interaction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_tags',
            field=models.ManyToManyField(blank=True, to='recommendations.tag'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 31, 1, 59, 49, 971621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 1, 59, 49, 971621, tzinfo=datetime.timezone.utc)),
        ),
    ]
