# Generated by Django 6.0 on 2025-12-30 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_item_author_fr_item_author_uk_item_description_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='author_uk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 22, 2, 58, 607768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 22, 2, 58, 607768, tzinfo=datetime.timezone.utc)),
        ),
    ]
