# Generated by Django 6.0 on 2026-01-14 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_item_custom_tags_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='language',
            field=models.CharField(choices=[('language_en', 'English'), ('language_fr', 'French'), ('language_uk', 'Ukrainian')], default='language_en', max_length=15),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='language_level',
            field=models.CharField(blank=True, choices=[('beginner_reading_level', 'Beginner'), ('intermediate_reading_level', 'Intermediate'), ('advanced_reading_level', 'Advanced'), ('expert_reading_level', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 31, 2, 12, 12, 338423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 2, 12, 12, 338423, tzinfo=datetime.timezone.utc)),
        ),
    ]
