# Generated by Django 6.0 on 2025-12-30 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_item_author_fr_alter_item_author_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 22, 57, 40, 79368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 22, 57, 40, 79368, tzinfo=datetime.timezone.utc)),
        ),
    ]
