# Generated by Django 6.0 on 2026-02-01 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_update_language_level_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 0, 50, 5, 834569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 7, 0, 50, 5, 834569, tzinfo=datetime.timezone.utc)),
        ),
    ]
