# Generated by Django 6.0 on 2025-12-31 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_loan_member_item_favourited_by_loan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 15, 34, 10, 678800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 15, 34, 10, 678800, tzinfo=datetime.timezone.utc)),
        ),
    ]
