# Generated by Django 6.0 on 2026-05-29 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_loan_due_date_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 13, 19, 46, 47, 684534, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 30, 19, 46, 47, 684534, tzinfo=datetime.timezone.utc)),
        ),
    ]
