# Generated by Django 6.0 on 2026-05-31 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_loan_due_date_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 20, 1, 8, 46, 239530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 6, 1, 8, 46, 239530, tzinfo=datetime.timezone.utc)),
        ),
    ]
