# Generated by Django 6.0 on 2025-12-31 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_loan_due_date_alter_loan_loan_date_itemhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='unlimited_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 22, 9, 19, 904188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 22, 9, 19, 904188, tzinfo=datetime.timezone.utc)),
        ),
    ]
