# Generated by Django 6.0 on 2026-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendationextras',
            name='last_recommendation_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
