# Generated by Django 6.0 on 2026-01-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_loan_due_date_alter_loan_loan_date'),
        ('recommendations', '0002_alter_userrecommendationextras_last_recommendation_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.item'),
            preserve_default=False,
        ),
    ]
