# Generated by Django 6.0 on 2026-01-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_interaction_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='item',
        ),
    ]
