# Generated by Django 6.0 on 2026-01-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_loan_due_date_alter_loan_loan_date'),
        ('recommendations', '0004_remove_interaction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
